sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 13306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 16379
    password:
    database: 0

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8yY9xRZJwY
    access-key-secret: 8y9xRZJwY
    bucket-name: sky-take-out

